In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
pd.options.display.float_format = '{:.4f}'.format
pd.options.display.max_rows = 500   
pd.options.display.max_columns = 20   
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import roc_auc_score
from sklearn.metrics import confusion_matrix, precision_score, recall_score, accuracy_score, f1_score

In [2]:
df = pd.read_csv('230102_company3.csv')
df.drop(['기업명','기업구분','Unnamed: 0'], axis=1, inplace=True)
df

     기업구분코드   사원수      업력   입사율(%)   퇴사율(%)   이직율(%)     별점     추천
0    3.0000    52  4.0000 114.7100  64.7100  56.4100 4.3000 1.0000
1    3.0000   930 17.0000  89.9400  97.8400 108.7800 2.3000 0.0000
2    3.0000    20 10.0000  40.0000  30.0000  75.0000 3.0000 1.0000
3    3.0000   140  0.0000 120.0000 100.0000  83.3300 3.3000 1.0000
4    3.0000     3  6.0000  33.3300   0.0000   0.0000 3.0000 1.0000
5    3.0000    67 23.0000  42.8600  50.0000 116.6600 2.4000 0.0000
6    3.0000    80  4.0000 164.2900  84.2900  51.3100 2.3000 0.0000
7    3.0000    75 12.0000  89.1900  62.1600  69.6900 2.1000 0.0000
8    3.0000    27 10.0000  11.1100   3.7000  33.3000 4.5000 1.0000
9    3.0000    39 22.0000  12.5000  25.0000 200.0000 3.3000 1.0000
10   3.0000    17  4.0000  12.5000  25.0000 200.0000 3.3000 1.0000
11   3.0000   173  0.0000  46.5300  27.7800  59.7000 2.8000 1.0000
12   3.0000    17  8.0000  29.4100  29.4100 100.0000 4.1000 1.0000
13   3.0000    82  0.0000  91.0000  70.0000  76.9200 2.5000 0.0000
14   3.0000    40 16.0000  28.2100  15.3800  54.5200 3.6000 1.0000
15   3.0000   115 14.0000  82.8800  82.8800 100.0000 2.2000 0.0000
16   3.0000    68  0.0000  35.5900  33.9000  95.2500 3.2000 1.0000
17   3.0000    42  0.0000  20.0000  35.5600 177.8000 2.6000 0.0000
18   3.0000   177  0.0000  91.2300  35.0900  38.4600 2.4000 0.0000
19   3.0000    29  0.0000  29.0300  38.7100 133.3400 3.0000 1.0000
20   3.0000    20  0.0000 146.0000  93.0000  63.7000 1.7000 0.0000
21   3.0000    33  0.0000  67.7400  64.5200  95.2500 4.6000 1.0000
22   3.0000    30  0.0000  85.0000  53.0000  62.3500 2.8000 1.0000
23   3.0000    21  0.0000  44.0000  39.0000  88.6400 1.7000 0.0000
24   3.0000    93 17.0000  58.1800  52.7300  90.6300 3.2000 1.0000
25   3.0000    82  6.0000 128.3000 132.0800 102.9500 2.5000 0.0000
26   3.0000    20 12.0000 128.3000 132.0800 102.9500 1.8000 0.0000
27   3.0000    28  5.0000  56.7600  40.5400  71.4200 3.3000 1.0000
28   3.0000   278  7.0000  50.0000  40.5000  81.0000 2.7000 1.0000
29   3.0000    62  5.0000  78.0000  62.0000  79.4900 2.8000 1.0000
30   3.0000   104  6.0000 136.3600  93.1800  68.3300 2.6000 0.0000
31   3.0000    36  0.0000 166.6700  40.0000  24.0000 2.3000 0.0000
32   3.0000    15  8.0000  66.6700  44.4400  66.6600 1.9000 0.0000
33   3.0000   229  0.0000  24.8900  19.9100  79.9900 3.2000 1.0000
34   3.0000    44  0.0000  86.8400  55.2600  63.6300 3.3000 1.0000
35   3.0000    16  6.0000  30.0000  55.0000 183.3300 3.3000 1.0000
36   3.0000    42  9.0000  88.5200  80.3300  90.7500 2.9000 1.0000
37   3.0000    28  0.0000  69.5700  56.5200  81.2400 3.2000 1.0000
38   3.0000    18  0.0000 400.0000 250.0000  62.5000 4.5000 1.0000
39   3.0000   235  0.0000  48.1000  35.7100  74.2400 3.3000 1.0000
40   3.0000    16  0.0000  97.0000  72.0000  74.2300 2.6000 0.0000
41   3.0000    78  9.0000  43.4200  65.7900 151.5200 2.8000 1.0000
42   3.0000    54 24.0000 216.6700  83.3300  38.4600 2.4000 0.0000
43   3.0000    63  0.0000  43.0000  24.0000  55.8100 3.4000 1.0000
44   3.0000    32  7.0000 176.1900  57.1400  32.4300 2.5000 0.0000
45   3.0000    26  0.0000  27.5900  44.8300 162.4900 3.0000 1.0000
46   3.0000    12  0.0000  15.3800  15.3800 100.0000 4.3000 1.0000
47   3.0000   134  0.0000  81.7200  40.8600  50.0000 3.2000 1.0000
48   3.0000    11  4.0000 115.3800 161.5400 140.0100 3.5000 1.0000
49   3.0000   297 13.0000 104.2200  70.0400  67.2000 2.6000 0.0000
50   3.0000   145 15.0000  46.8100  29.0800  62.1200 2.9000 1.0000
51   3.0000   133 16.0000  98.0600  65.0500  66.3400 2.4000 0.0000
52   3.0000    24 13.0000 122.2200  94.4400  77.2700 2.9000 1.0000
53   3.0000    33 15.0000  33.0000  33.0000 100.0000 2.6000 0.0000
54   3.0000   635 15.0000  50.7600  61.0100 120.1900 1.8000 0.0000
55   3.0000    66 10.0000  51.5600  32.8100  63.6300 2.5000 0.0000
56   3.0000    17 13.0000 366.6700 251.8500  68.6900 3.6000 1.0000
57   3.0000    56 11.0000  41.4600  31.7100  76.4800 4.1000 1.0000
58   3.0000    71 14.0000  28.7900  30.3000 105.2400 3.4000 1.0000
59   3.0000   215 20.0000  26.8900  29.2500 108.7800 2.4000 0.0000
60   3.0000   110 23.0000  19.0900  20.0000 104.7700 3.0000 1.0000
61   3.0000   143 14.0000 123.9100  68.4800  55.2700 1.0000 0.0000
62   3.0000    26  0.0000  31.4300  40.0000 127.2700 3.3000 1.0000
63   3.0000    13  5.0000  77.7800  33.3300  42.8500 4.3000 1.0000
64   3.0000    83 12.0000  38.1000  38.1000 100.0000 2.3000 0.0000
65   3.0000     7  2.0000 316.6700 316.6700 100.0000 2.5000 0.0000
66   3.0000    99  4.0000 231.2500  95.8300  41.4400 4.0000 1.0000
67   3.0000    14 16.0000  30.2600  26.3200  86.9800 2.3000 0.0000
68   3.0000   317 12.0000  89.8600  31.1200  34.6300 3.1000 1.0000
69   3.0000    35  9.0000  32.0000  23.0000  71.8800 3.3000 1.0000
70   3.0000    20  0.0000  69.5700  52.1700  74.9900 1.8000 0.0000
71   3.0000    14  6.0000  38.1000  71.4300 187.4800 2.1000 0.0000
72   3.0000    23 14.0000  30.7700  42.3100 137.5000 3.0000 1.0000
73   3.0000    11  7.0000  31.2500  50.0000 160.0000 5.0000 1.0000
74   3.0000   163 20.0000  41.3300  30.6700  74.2100 2.9000 1.0000
75   3.0000   222 23.0000  28.8600  22.8200  79.0700 2.1000 0.0000
76   3.0000    45  4.0000 109.6800  61.2900  55.8800 4.7000 1.0000
77   3.0000    19 14.0000 166.6700 140.0000  84.0000 1.7000 0.0000
78   3.0000    66 21.0000  24.6200  32.3100 131.2300 2.9000 1.0000
79   3.0000   224 18.0000  54.8200  39.0900  71.3100 2.2000 0.0000
80   3.0000   224  4.0000 141.6000  44.0000  31.0700 3.4000 1.0000
81   3.0000    95  4.0000  32.1000 129.6300 403.8300 2.4000 0.0000
82   3.0000    25 19.0000  11.5400  15.3800 133.2800 2.7000 1.0000
83   3.0000   943 10.0000 137.9600  39.2000  28.4100 2.7000 1.0000
84   3.0000    63 20.0000  34.3800  39.0600 113.6100 1.9000 0.0000
85   3.0000    24 20.0000  15.3800  11.5400  75.0300 2.6000 0.0000
86   3.0000    80 25.0000  27.8500  25.3200  90.9200 3.0000 1.0000
87   3.0000    20  4.0000  82.3500  52.9400  64.2900 2.0000 0.0000
88   3.0000   178  6.0000 101.1800  22.4900  22.2300 2.4000 0.0000
89   3.0000    40 21.0000  35.7100  47.6200 133.3500 2.6000 0.0000
90   3.0000   261 10.0000  90.3200  58.5300  64.8000 2.5000 0.0000
91   3.0000    20  5.0000   7.1400  28.5700 400.1400 4.0000 1.0000
92   3.0000    61 19.0000  60.0000  40.0000  66.6700 2.2000 0.0000
93   3.0000   162 20.0000  33.1200  16.5600  50.0000 2.5000 0.0000
94   3.0000    21  4.0000  62.5000  79.1700 126.6700 1.0000 0.0000
95   3.0000    32  3.0000 183.8700 151.6100  82.4500 1.8000 0.0000
96   3.0000    18 14.0000  35.0000  60.0000 171.4300 2.7000 1.0000
97   3.0000    15  3.0000 145.4500 118.1800  81.2500 2.0000 0.0000
98   3.0000   120  9.0000  91.7800  26.0300  28.3600 2.9000 1.0000
99   3.0000    77 14.0000  39.1300  15.9400  40.7400 2.9000 1.0000
100  3.0000    61 20.0000  64.7100  49.0200  75.7500 2.9000 1.0000
101  3.0000    39  6.0000 103.3300  60.0000  58.0700 3.4000 1.0000
102  3.0000    60  4.0000  70.9700  85.4800 120.4500 3.9000 1.0000
103  3.0000    77 22.0000  43.6400  36.3600  83.3200 3.2000 1.0000
104  3.0000   223 18.0000  22.4800  19.2700  85.7200 2.5000 0.0000
105  3.0000     2  7.0000  37.5000  19.1700  51.1200 2.8000 1.0000
106  3.0000    32  8.0000  36.6700  23.3300  63.6200 2.6000 0.0000
107  3.0000    52 14.0000  40.0000  22.2200  55.5500 3.3000 1.0000
108  3.0000    85  9.0000  72.5800  77.4200 106.6700 2.0000 0.0000
109  3.0000    52  7.0000  74.0700  59.2600  80.0100 3.4000 1.0000
110  3.0000    12 18.0000  12.5000  12.5000 100.0000 2.0000 0.0000
111  3.0000    50  7.0000  81.4000  79.0700  97.1400 2.7000 1.0000
112  3.0000    66 23.0000  41.6700  35.0000  83.9900 2.7000 1.0000
113  3.0000    70  7.0000 108.4700  42.3700  39.0600 4.4000 1.0000
114  3.0000    26 13.0000  35.1400  37.8400 107.6800 2.5000 0.0000
115  3.0000   185 19.0000  32.7100  45.7900 139.9900 2.5000 0.0000
116  3.0000   116 18.0000  30.3600  28.5700  94.1000 3.0000 1.0000
117  3.0000    45  4.0000 175.8600 127.5900  72.5500 2.7000 1.0000
118  3.0000     3  6.0000  28.5700  42.8600 150.0200 2.5000 0.0000
119  3.0000    60 21.0000  43.1000  44.8300 104.0100 3.3000 1.0000
120  3.0000    60 17.0000  42.8600  20.4100  47.6200 2.7000 1.0000
121  3.0000    12 20.0000  54.0000  58.0000 107.4100 2.5000 0.0000
122  2.0000   283 14.0000  27.1800  25.0900  92.3100 2.5000 0.0000
123  2.0000   739 37.0000   9.6800  11.6100 119.9400 3.3000 1.0000
124  2.0000   197 22.0000  55.4900  26.0100  46.8700 2.9000 1.0000
125  2.0000    45 28.0000  27.0000  13.0000  48.1500 2.7000 1.0000
126  2.0000  9658 21.0000 106.6300  99.0500  92.8900 2.6000 0.0000
127  2.0000   200 55.0000  44.6900  30.1700  67.5100 2.0000 0.0000
128  2.0000   321 10.0000  43.5900  27.8400  63.8700 3.3000 1.0000
129  2.0000   320 28.0000  16.0000  19.0000 118.7500 2.9000 1.0000
130  2.0000   141 22.0000  37.2400  35.8600  96.2900 2.7000 1.0000
131  2.0000   900  4.0000 108.8900  32.8900  30.2000 2.7000 1.0000
132  2.0000   106  1.0000  63.2200  35.6300  56.3600 3.8000 1.0000
133  2.0000   524 21.0000  57.8900  40.4100  69.8000 2.7000 1.0000
134  2.0000   219 39.0000  26.8200  20.0000  74.5700 3.0000 1.0000
135  2.0000   643 30.0000  37.9700  39.5300 104.1100 2.3000 0.0000
136  2.0000  1431  7.0000  79.0300  64.3400  81.4100 2.5000 0.0000
137  2.0000    78 19.0000  70.0000  62.5000  89.2900 2.1000 0.0000
138  2.0000  1274 40.0000  52.7200  39.8300  75.5500 3.1000 1.0000
139  2.0000   341  8.0000  53.2700  44.1200  82.8200 3.3000 1.0000
140  2.0000   220 22.0000  46.0500  37.2100  80.8000 3.2000 1.0000
141  2.0000   755  9.0000  29.7400  29.4800  99.1300 2.4000 0.0000
142  2.0000    32 24.0000  14.7100  23.5300 159.9600 2.5000 0.0000
143  2.0000   490  9.0000  23.0000  19.6200  85.3000 2.2000 0.0000
144  2.0000   791 20.0000  25.7700  17.6000  68.3000 3.3000 1.0000
145  1.0000  5376 38.0000  11.7100  12.3100 105.1200 4.0000 1.0000
146  1.0000   333 25.0000  24.5300  19.5700  79.7800 2.9000 1.0000
147  1.0000   533 22.0000  31.3600  19.4900  62.1500 2.5000 0.0000
148  1.0000    53  9.0000  25.0000  50.0000 200.0000 2.2000 0.0000
149  1.0000  1140 21.0000  26.0000  10.0000  38.4600 3.7000 1.0000
150  1.0000   553 17.0000  19.4000  20.1500 103.8700 2.5000 0.0000
151  1.0000  6603 35.0000  14.3000  10.8300  75.7300 3.1000 1.0000
152  1.0000    54  6.0000  31.4800  20.3700  64.7100 3.4000 1.0000
153  1.0000   217  6.0000  15.9800  26.9400 168.5900 3.0000 1.0000
154  1.0000   252  2.0000  90.3800  42.2600  46.7600 4.2000 1.0000
155  1.0000  1169 37.0000  24.6900  30.4900 123.4900 2.7000 1.0000
156  4.0000  1885 55.0000  20.1800  19.8000  98.1200 2.4000 0.0000
157  4.0000   117 25.0000  44.8600  38.3200  85.4200 2.7000 1.0000
158  4.0000    83 24.0000  11.9000  13.1000 110.0800 2.5000 0.0000
159  4.0000   197 27.0000  40.8000  20.6900  50.7100 2.8000 1.0000
160  4.0000    78 22.0000  30.7700  32.0500 104.1600 2.5000 0.0000
161  4.0000   237 26.0000  12.3500  21.8100 176.6000 1.9000 0.0000
162  4.0000   222 22.0000  18.9400  23.7900 125.6100 2.8000 1.0000
163  4.0000   242 12.0000  22.0800  30.8300 139.6300 2.2000 0.0000
164  4.0000   120 23.0000  39.7800  15.0500  37.8300 3.0000 1.0000
165  4.0000    27 22.0000  28.1300  12.5000  44.4400 2.1000 0.0000
166  4.0000   131 23.0000   9.1600   6.8700  75.0000 2.8000 1.0000
167  4.0000   111 19.0000  36.8400  20.0000  54.2900 3.2000 1.0000
168  4.0000   187 29.0000  48.3100  43.8200  90.7100 3.3000 1.0000
169  4.0000    36 33.0000   8.8200  23.5300 266.7800 2.2000 0.0000
170  4.0000   115 27.0000   8.7700   5.2600  59.9800 2.2000 0.0000
171  4.0000  1686 45.0000   7.2500   8.0000 110.3400 3.7000 1.0000
172  4.0000   193 25.0000  80.6100  70.9200  87.9800 2.5000 0.0000
173  4.0000    25  6.0000  42.3100  84.6200 200.0000 3.0000 1.0000

In [3]:
X = df.drop(columns='추천')
Y = df['추천']

# x_train, x_test 데이터 생성
x_train, x_test, y_train, y_test  = train_test_split(X, Y, test_size=0.2, stratify= Y, random_state=0)

x_train.shape, y_train.shape, x_test.shape

((139, 7), (139,), (35, 7))

In [4]:
scaler = StandardScaler()
x_train = pd.DataFrame(scaler.fit_transform(x_train),columns=x_train.columns)
x_test = pd.DataFrame(scaler.transform(x_test),columns=x_test.columns)

x_train.describe().T

          count    mean    std     min     25%     50%     75%    max
기업구분코드 139.0000 -0.0000 1.0036 -2.6867  0.2195  0.2195  0.2195 1.6727
사원수    139.0000 -0.0000 1.0036 -0.3065 -0.2774 -0.2382 -0.1185 8.4850
업력     139.0000 -0.0000 1.0036 -1.2390 -0.7399 -0.1501  0.6665 3.7515
입사율(%) 139.0000  0.0000 1.0036 -0.9812 -0.6121 -0.3597  0.3922 5.3723
퇴사율(%) 139.0000  0.0000 1.0036 -1.0662 -0.5957 -0.2615  0.2995 6.3101
이직율(%) 139.0000 -0.0000 1.0036 -1.3048 -0.5471 -0.2226  0.2078 5.6733
별점     139.0000 -0.0000 1.0036 -2.6900 -0.6547 -0.0732  0.6537 3.1251

In [5]:
# train score, test score, roc_auc_score 
def get_scores(model, xtrain, xtest, ytrain, ytest):
    A = model.score(xtrain, ytrain)
    B = model.score(xtest, ytest)
    ypred = model.predict(xtest)
    C = roc_auc_score(ytest, ypred)  
    return '{:.4f} {:.4f} {:.4f}'.format(A, B, C)
# 모델선택 
def make_models(xtrain, xtest, ytrain, ytest):
    model1 = LogisticRegression(max_iter=1000).fit(xtrain, ytrain)
    print('model1', get_scores(model1, xtrain, xtest, ytrain, ytest))
    for k in range(1, 10):
        model2 = KNeighborsClassifier(k).fit(xtrain, ytrain)
        print('model2', k, get_scores(model2, xtrain, xtest, ytrain, ytest))

    # overfitting
    model3 = DecisionTreeClassifier(random_state=0).fit(xtrain, ytrain)
    print('model3', get_scores(model3, xtrain, xtest, ytrain, ytest))

    # overfitting 해결
    for d in range(3, 8):
        model3 = DecisionTreeClassifier(max_depth=d,random_state=0).fit(xtrain, ytrain)
        print('model3', d, get_scores(model3, xtrain, xtest, ytrain, ytest))

    # overfitting
    model4 = RandomForestClassifier(random_state=0).fit(xtrain, ytrain)
    print('model4', get_scores(model4, xtrain, xtest, ytrain, ytest))

    # overfitting 해결
    for d in range(3, 8):
        model4 = RandomForestClassifier(500, max_depth=d, random_state=0).fit(xtrain, ytrain)
        print('model4', d, get_scores(model4, xtrain, xtest, ytrain, ytest))

    model5 = XGBClassifier(eval_metric='logloss', use_label_encoder=False).fit(xtrain, ytrain)
    print('model5', get_scores(model5, xtrain, xtest, ytrain, ytest))

In [8]:
#성능평가 
def get_other_scores(model, xtest, ytest):
    y_pred = model.predict(xtest)
    accuracy = accuracy_score(ytest, y_pred)
    precision = precision_score(ytest, y_pred)
    recall = recall_score(ytest, y_pred)
    f1 = f1_score(ytest, y_pred)
    print(f'accuracy  : {accuracy:7.4f}')
    print(f'precision : {precision:7.4f}')
    print(f'recall    : {recall:7.4f}')
    print(f'f1        : {f1:7.4f}')

In [9]:
make_models(x_train,x_test,y_train,y_test)

model1 0.9856 0.9714 0.9750
model2 1 1.0000 0.8857 0.8833
model2 2 0.9209 0.7143 0.7417
model2 3 0.9424 0.8000 0.7917
model2 4 0.9353 0.8000 0.8000
model2 5 0.8849 0.8571 0.8500
model2 6 0.8777 0.8000 0.8083
model2 7 0.8489 0.8571 0.8583
model2 8 0.8849 0.8857 0.8917
model2 9 0.8705 0.8571 0.8500
model3 1.0000 1.0000 1.0000
model3 3 1.0000 1.0000 1.0000
model3 4 1.0000 1.0000 1.0000
model3 5 1.0000 1.0000 1.0000
model3 6 1.0000 1.0000 1.0000
model3 7 1.0000 1.0000 1.0000
model4 1.0000 1.0000 1.0000
model4 3 1.0000 1.0000 1.0000
model4 4 1.0000 1.0000 1.0000
model4 5 1.0000 1.0000 1.0000
model4 6 1.0000 1.0000 1.0000
model4 7 1.0000 1.0000 1.0000
model5 1.0000 1.0000 1.0000

In [10]:
# model1 = LogisticRegression(max_iter=1000).fit(x_train, y_train)
# model2 = KNeighborsClassifier(8).fit(x_train, y_train)

In [33]:
model = LogisticRegression(max_iter=1000).fit(x_train, y_train)
print(get_scores(model, x_train, x_test, y_train, y_test))  # train score, test score, roc_auc_score 
get_other_scores(model,x_test,y_test)

0.9856 0.9714 0.9750
accuracy  :  0.9714
precision :  1.0000
recall    :  0.9500
f1        :  0.9744

In [34]:
y_pred = model.predict(x_test)
label=['비추천', '추천']
a = confusion_matrix(y_test, y_pred)
b = pd.DataFrame(a, columns=label, index=label)
b

     비추천  추천
비추천   15   0
추천     1  19

In [35]:
model = KNeighborsClassifier(8).fit(x_train, y_train)
print(get_scores(model, x_train, x_test, y_train, y_test))  # train score, test score, roc_auc_score 
get_other_scores(model,x_test,y_test)

0.8849 0.8857 0.8917
accuracy  :  0.8857
precision :  0.9444
recall    :  0.8500
f1        :  0.8947

In [36]:
y_pred = model.predict(x_test)
label=['비추천', '추천']
a = confusion_matrix(y_test, y_pred)
b = pd.DataFrame(a, columns=label, index=label)
b

     비추천  추천
비추천   14   1
추천     3  17